### ISSUE TITLE
Fix python error "TypeError: unsupported operand type(s) for -: 'str' and 'str'" 

### ISSUE THREAD

**Issue by thariyarox** [thariyarox/hacktoberfest-CoinSpot-Data-Crawler#18]
When running the process_csv.py file [1] with python3 process_cvs.py command, it gives the "TypeError: unsupported operand type(s) for -: 'str' and 'str'"  error. Need to fix it.

[1] https://github.com/thariyarox/CoinSpot-Data-Crawler/blob/master/processors/process_csv.py

**Comment by logesr** [comment]
I can take this up!

**Comment by thariyarox** [comment]
@logesr Great ! I've assigned the issue to you.

**Comment by logesr** [comment]
@thariyarox python3 process_csv.py seems to be working fine for me. I am getting the output without any exception. I have pulled the code from master branch. Am I missing any code here?

**Comment by thariyarox** [comment]
@logesr Can you apply the fix in https://github.com/thariyarox/CoinSpot-Data-Crawler/pull/17 to the crawler/run.py and see if it still works ?

**Comment by logesr** [comment]
yes @thariyarox it works there too.. However, I would suggest to use relative path in #17 as the data is generated in different places depending on the folder we run our command from

**Comment by cskinner74** [comment]
@logesr good to hear it's still working. Do you have a suggestion for how to best address the calls to each script? I went with relative paths from the run.py file since that seemed to be the easiest way to get to the other folders, but I definitely see that causing issues if run.py isn't called from the same folder. Wasn't sure if there was a good way to use absolute paths in this case.

**Comment by logesr** [comment]
@wskinner74 You were right. I was able to reproduce the issue with upgraded python.

@thariyarox I have raised a pull request to fix both file path and type error issue.

**Comment by cskinner74** [comment]
@logesr ah I see what you mean now, thanks for fixing that!
